### ISSUE TITLE
Inclusão de Documentação (TAP) do Projeto

### ISSUE THREAD

**Issue by JoaoEduardoP** [PI1-2024-1/PI1-2024-1#2]
Esta issue destina-se a coordenar a inclusão da documentação do projeto. 

Tarefas:

- [x] #4
- [x]  Implementar o Projeto Conceitual na documentação do Projeto.
- [x]  Implementar o Cronograma na documentação do Projeto.

Critérios de Aceitação:

A documentação deve ser clara, concisa e acessível a qualquer pessoa interessada no projeto.
Todas as seções da documentação devem ser completas, cobrindo todos os aspectos relevantes do projeto (feito até o momento).

**Comment by pedroMADBR** [comment]
Tudo corretamente feito, parabéns!
